channels:
    - conda-forge
name: py36
dependencies:
    - pip
    - python=3.6
    - setuptools
    - wheel
    - pip:
        - Sphinx
        - sphinx_celery
        - sphinxcontrib-asyncio
        - sphinx-autodoc-annotation
        - alabaster
